# Generated by Django 6.0.1 on 2026-02-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=False, verbose_name='Activar para ver en Web'),
        ),
    ]
