# Generated by Django 6.0.1 on 2026-02-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_datospersonales_activarparaqueseveaenfront'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
