# Generated by Django 6.0.1 on 2026-01-07 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_datospersonales_experiencialaboral_habilidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='logros',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='cargodesempenado',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='nombrempresa',
            new_name='puesto',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='archivo_cv_pdf',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='sitioweb',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='telefonofijo',
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='actualidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales'),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nivel',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=100)),
                ('fecha_obtencion', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='certificados/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales')),
            ],
        ),
    ]
