# Generated by Django 6.0.1 on 2026-01-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_logros_experiencialaboral_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='certificados/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificado',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nivel',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50),
        ),
    ]
