# Generated by Django 6.0.1 on 2026-02-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_datospersonales_descripcionperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
