# Generated by Django 6.0.1 on 2026-01-07 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_datospersonales_foto_datospersonales_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('institucion', models.CharField(max_length=150)),
                ('fecha_graduacion', models.DateField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales')),
            ],
        ),
    ]
