# Generated by Django 6.0.1 on 2026-02-03 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_datospersonales_descripcionperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosacademicos',
            name='descripcion',
            field=models.CharField(max_length=800),
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_habilidad', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Blanda', 'Habilidad Blanda'), ('Tecnica', 'Habilidad Técnica')], default='Tecnica', max_length=50)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='LenguajeProgramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel_porcentaje', models.IntegerField(default=50, help_text='Nivel del 1 al 100')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales')),
            ],
        ),
    ]
