# Generated by Django 6.0.1 on 2026-01-07 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_habilidad_nivel_alter_habilidad_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educacion',
            name='titulo',
        ),
    ]
