# Generated by Django 6.0.1 on 2026-02-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_cursosrealizados_rutacertificado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionvisible',
            options={'verbose_name': 'Configuración de Visibilidad', 'verbose_name_plural': 'Configuración de Visibilidad'},
        ),
        migrations.AlterField(
            model_name='configuracionvisible',
            name='mostrar_cursos',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Cursos?'),
        ),
        migrations.AlterField(
            model_name='configuracionvisible',
            name='mostrar_garage',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Garage?'),
        ),
        migrations.AlterField(
            model_name='configuracionvisible',
            name='mostrar_reconocimientos',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Reconocimientos?'),
        ),
    ]
