# Generated by Django 6.0.1 on 2026-02-02 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_educacion_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionVisible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_garage', models.BooleanField(default=True)),
                ('mostrar_cursos', models.BooleanField(default=True)),
                ('mostrar_reconocimientos', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Botones',
                'verbose_name_plural': 'Configuración de Botones',
            },
        ),
        migrations.CreateModel(
            name='ProductoGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='garage/')),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Medio Usado', 'Medio Usado'), ('Usado', 'Usado (Buen Estado)')], default='Nuevo', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_publicado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='fecha_obtencion',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='actualidad',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='fecha_inicio',
        ),
        migrations.AlterField(
            model_name='certificado',
            name='institucion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_fotos/'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='institucion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='empresa',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='puesto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lenguaje',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('institucion_otorga', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reconocimientos/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales')),
            ],
        ),
    ]
