# Generated by Django 6.0.1 on 2026-02-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_configuracionvisible_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionvisible',
            options={'verbose_name': 'Configuración de Visibilidad', 'verbose_name_plural': 'Configuraciones de Visibilidad'},
        ),
    ]
