# Generated by Django 6.0.1 on 2026-02-02 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_configuracionvisible_productogarage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursosRealizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrerecurso', models.CharField(max_length=100)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('totalhoras', models.IntegerField()),
                ('descripcioncurso', models.CharField(max_length=100)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(max_length=100)),
                ('telefonocontactoauspicia', models.CharField(max_length=60)),
                ('emailempresapatrocinadora', models.CharField(max_length=60)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrerecurso', models.CharField(max_length=100)),
                ('clasificador', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosLaborales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('fechaproducto', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='garage/')),
            ],
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='educacion',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='habilidad',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='lenguaje',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='ProductoGarage',
        ),
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='perfil',
            new_name='idperfilconqueestaactivo',
        ),
        migrations.RenameField(
            model_name='reconocimiento',
            old_name='fecha',
            new_name='fechareconocimiento',
        ),
        migrations.RenameField(
            model_name='reconocimiento',
            old_name='perfil',
            new_name='idperfilconqueestaactivo',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='id',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='institucion_otorga',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='titulo',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='direcciontrabajo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='estadocivil',
            field=models.CharField(default='soltero', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='idperfil',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='lugarnacimiento',
            field=models.CharField(default='Ecuador', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(default='Ecuatoriano', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(choices=[('H', 'M'), ('M', 'F')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='sitioweb',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='cargodesempenado',
            field=models.CharField(default='Empleado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
            field=models.CharField(default='Funciones generales', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='emailempresa',
            field=models.CharField(default='bermelloj21@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='fechafingestion',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='fechainiciogestion',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='lugarempresa',
            field=models.CharField(default='Ecuador', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='nombrecontactoempresarial',
            field=models.CharField(default='Contacto', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='nombrempresa',
            field=models.CharField(default='Empresa X', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='telefonocontactoempresarial',
            field=models.CharField(default='0967450960', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='activarparaqueseveaenfront',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='descripcionreconocimiento',
            field=models.CharField(default='Descripción', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='entidadpatrocinadora',
            field=models.CharField(default='Entidad', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='nombrecontactoauspicia',
            field=models.CharField(default='Nombre de Contacto', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='rutacertificado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='telefonocontactoauspicia',
            field=models.CharField(default='0999999999', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='tiporeconocimiento',
            field=models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombres',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='cursosrealizados',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales'),
        ),
        migrations.AddField(
            model_name='productosacademicos',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales'),
        ),
        migrations.AddField(
            model_name='productoslaborales',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales'),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='idperfilconqueestaactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.datospersonales'),
        ),
        migrations.DeleteModel(
            name='Certificado',
        ),
        migrations.DeleteModel(
            name='Educacion',
        ),
        migrations.DeleteModel(
            name='Habilidad',
        ),
        migrations.DeleteModel(
            name='Lenguaje',
        ),
    ]
