# Generated by Django 6.0.1 on 2026-02-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_configuracionvisible_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionvisible',
            options={'verbose_name': 'Ajustes de Visibilidad Web', 'verbose_name_plural': 'Ajustes de Visibilidad Web'},
        ),
        migrations.AddField(
            model_name='configuracionvisible',
            name='mostrar_experiencia',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Experiencia Laboral?'),
        ),
        migrations.AddField(
            model_name='configuracionvisible',
            name='mostrar_habilidades',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Habilidades?'),
        ),
        migrations.AddField(
            model_name='configuracionvisible',
            name='mostrar_lenguajes',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Lenguajes de Programación?'),
        ),
        migrations.AddField(
            model_name='configuracionvisible',
            name='mostrar_productos_academicos',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Productos Académicos?'),
        ),
        migrations.AddField(
            model_name='configuracionvisible',
            name='mostrar_productos_laborales',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Productos Laborales?'),
        ),
        migrations.AddField(
            model_name='configuracionvisible',
            name='mostrar_sobre_mi',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Sobre Mí?'),
        ),
        migrations.AlterField(
            model_name='configuracionvisible',
            name='mostrar_cursos',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Cursos Realizados?'),
        ),
        migrations.AlterField(
            model_name='configuracionvisible',
            name='mostrar_garage',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Botón de Garage?'),
        ),
    ]
