# Generated by Django 6.0.1 on 2026-02-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_configuracionvisible_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionvisible',
            options={'verbose_name': 'Configuración de Visibilidad', 'verbose_name_plural': 'Configuraciones de Visibilidad'},
        ),
        migrations.RemoveField(
            model_name='configuracionvisible',
            name='mostrar_experiencia',
        ),
        migrations.RemoveField(
            model_name='configuracionvisible',
            name='mostrar_habilidades',
        ),
        migrations.RemoveField(
            model_name='configuracionvisible',
            name='mostrar_lenguajes',
        ),
        migrations.RemoveField(
            model_name='configuracionvisible',
            name='mostrar_productos_academicos',
        ),
        migrations.RemoveField(
            model_name='configuracionvisible',
            name='mostrar_productos_laborales',
        ),
        migrations.RemoveField(
            model_name='configuracionvisible',
            name='mostrar_sobre_mi',
        ),
        migrations.AlterField(
            model_name='configuracionvisible',
            name='mostrar_cursos',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Cursos?'),
        ),
        migrations.AlterField(
            model_name='configuracionvisible',
            name='mostrar_garage',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar Garage?'),
        ),
    ]
